# lazygit — Monokai Pro Ristretto theme + Nerd Font
gui:
  nerdFontsVersion: "3"
  showFileTree: true
  showRandomTip: false
  theme:
    activeBorderColor:
      - "#f38d70"
      - bold
    inactiveBorderColor:
      - "#72696a"
    optionsTextColor:
      - "#85dacc"
    selectedLineBgColor:
      - "#403838"
    cherryPickedCommitBgColor:
      - "#5b5353"
    cherryPickedCommitFgColor:
      - "#85dacc"
    unstagedChangesColor:
      - "#fd6883"
    defaultFgColor:
      - "#fff1f3"
    searchingActiveBorderColor:
      - "#f9cc6c"
  authorColorDefault: "#f9cc6c"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
